#using travis ssh key
language: c
script: bash ./build.sh
compiler:
    - gcc
after_failure: cat build/git_description.c
branches:
    only:
    - master
    - integration
    - travis
notification:
    email:
    - jchen@sayhello.com
        

