language: c
script: ./tools/build.sh
compiler:
    - gcc
#installs 32bit dependencies
before_script: sudo apt-get update && sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0
after_failure: cat build/git_description.c
branches:
    only:
    - master
    - integration
    - travis
notification:
    email:
    - jchen@sayhello.com
    hipchat:
        rooms:
            - KBYAKZQ0oG2SFmI0YyPpz3RoUKe0v6dQLd9kF8CS@Ops
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
        

